[build-system]
requires = ["setuptools==82.0.1"]
build-backend = "setuptools.build_meta"

[project]
name = "command-interpreter"
version = "0.0.2"
authors = [
    {name="Machina Ratiocinatrix", email="machina.ratio@gmail.com"},
    {name="Alexander Fedotov", email="alex.fedotov@aol.com"}
]
description = "A Machine that interprets arbitrary textual commands."
readme = "README.md"
requires-python = ">=3.10"
classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
]
keywords = ["command-interpreter"]
dependencies = [
    "pyyaml == 6.0.3"
]

[project.scripts]
command-interpreter = "command_interpreter.cli:run"

[project.urls]
"Homepage" = "https://github.com/command-interpreter/command-interpreter"

[dependency-groups]
dev = ["pytest>=8.0.0"]